### ISSUE TITLE
java-admin-client acting weird

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/docker-existdb#45]
`docker exec exist java -jar start.jar client --no-gui`
results in an endless stream of `exist:/db>` to be put into the calling shell.

Am i doing it wrong, or whats going on?

**Comment by grantmacken** [comment]
Looks like a readline problem.
It most likely can be fixed if with if we include the relevant `so`.  As mentioned in the docs `lib/core/libJavaReadline` is  required. It also says it depends on `gnu readline` itself. This is heading towards rebuilding a shell environment to enable an *interactive* client.  Since our base image `gcr.io/distroless/java` has a removed shell environment, I am not sure if we want to add readline etc.

As shown in the travis tests, the client is usable for issuing commands, 
however as it stands now it can not be used as an interactive shell.

**Comment by duncdrum** [comment]
agreed on not rebuilding a shell into gcr. I ll add a note to the readme, about interactive mode

**Comment by duncdrum** [comment]
```bash
docker exec trusting_torvalds java -jar start.jar client --no-gui
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8   -Djava.awt.headless=true   -Dorg.exist.db-connection.cacheSize=256M   -Dorg.exist.db-connection.pool.max=20   -XX:+UnlockExperimentalVMOptions   -XX:+UseCGroupMemoryLimitForHeap   -XX:+UseG1GC   -XX:+UseStringDeduplication   -XX:MaxRAMFraction=1
eXist version 5.0.0-SNAPSHOT (83eeb543a), Copyright (C) 2001-2018 The eXist-db Project
eXist-db comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; for details read the license file.

16 Dec 2018 10:13:35,694 [main] WARN  (Log.java [logr]:117) - Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information) 
Connecting to database...
Connected :-)

type help or ? for help.
exist:/db> quit.
```
very nice, thank you @adamretter
