### ISSUE TITLE
Extension lib changes lead to failing builds

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/docker-existdb#55]
![screenshot 2019-02-10 at 15 56 54](https://user-images.githubusercontent.com/6205362/52535291-9f9ad680-2d4c-11e9-9444-f728331611e1.png)

**Comment by grantmacken** [comment]
@duncdrum 
Some thoughts: I think this points to the fragility of the approach we have adopted.
A default build occurs via build.sh, then to get a minimal build we try to copy over into distroless OS,
the minimum files to to bring up eXist in a workable state.
This copy list comes from @adamretter in his original script.
I think we modified, the copy operation a little but not much. 
e,g, betterform posed a problem, so we copied the whole dir.
When project layout changes occur, we will get problem as raised by this issue.
What I would like to see, is instead of the large copy over list,  we have the work carried out by `build.sh` itself,  with its build arg calling a 'minimal docker ant build'.
See [minimal.xml build](https://github.com/eXist-db/exist/blob/develop/build/scripts/minimal.xml)
In this ant file, it is mainly just a copy operation, 
so like this ant build, we could have a specific docker ant build.
Like the other ant builds, this work would be in the main main eXist repo and tied to its commit -release cycle.

Our Dockerfile, then would have a simpler copy operation, less prone to failure due to eXist project layout refactoring.

**Comment by duncdrum** [comment]
@grantmacken agree. We initially planned to switch the exist build system to maven, after the release of 5.0.0. Due a delay with 5.0.0 we are now seeing changes to the build system in preparation of maven while we are still in the 4.x phase.

With the switch to maven, I'll do a complete rewrite of the way we get to the minimal image. But in the mean time our official images need to work.
