### ISSUE TITLE
Problem connection with oxygen

### ISSUE THREAD

**Issue by gabylan12** [eXist-db/docker-existdb#61]
I create an instance existdb/existdb:4.5.0. the port 8080 is mapped with 30088.
I tried to connect against xmldb:exist://localhost:30088/exist/xmlrpc but i have timeout connection.
I have to do some extra configuration?

**Comment by duncdrum** [comment]
what version of oXygen are you using? Older version might have problems with connections to exist `4.5.0` irrespective of docker. `v21` connects to `4.5.0 and up` without problems (i just tried). 

Port 30088 looks like a randomly generated port, if you don't want to configure a new connection every time you start a container.  I'd recommend picking one port e.g. `8765` for all your exist docker work on that machine. Simply start the image via `docker run -dit -p 8765:8080 existdb/existdb:4.5.0`.

Use the oxygen connection wizard to create the connection. No further steps will be necessary. 

However, if you recently updated the image to a new exist version, you might have to delete the old connection and establish a new one, since the connection details can change between versions. So connections configured with `4.5.0` are incompatible with `4.6.1`.

I have sometimes noticed a need to restart Oxygen for new connection settings to take effect.

**Comment by gabylan12** [comment]
I could connect, it was a problem with my solution.
The container was published inside a pod in kubernetes, running inside a virtual machine.
I change localhost with my local ip and works fine.
thanks a lot!
